### ISSUE TITLE
https://github.com/users/Dorcas126/projects/9

### ISSUE THREAD

**Issue by H-Ramalan** [Dorcas126/Recipe-app#13]
We are two members in the group @H-Ramalan and @Dorcas126 
https://github.com/users/Dorcas126/projects/9

**Comment by Abenezer-Tilahun** [comment]
Hi @H-Ramalan @Dorcas126 

Great job for implemented  the some of the Project Requirement  , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ Good Job for Create tasks on your Kanban board based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md)
✔️ Good Job for Provide the link to their GitHub project and information about the number of people in your group.


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [x] Kindly make sure that **all cards are assigned to team members**. There should see a circle with the user's avatar on each card. See the example below.

![kanban](https://github.com/Dorcas126/Recipe-app/assets/93598189/e3c2f454-37be-447d-8d0d-904799acce40)

- [x] Kindly make sure that tasks are distributed in a fair way, Sum the number of points for each student (`[Xpt]` in the card title) is not should be greater than difference >= 5 points) more or less points than others.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
